### ISSUE TITLE
/tmp conflict

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcmetrics#256]
On aims4 there was a permissions conflict related to the use of cdscan while running diags. We need to resolve this to allow for multiple users.

**Comment by painter1** [comment]
This sort of thing is almost irreproducible because it depends on the timing and content of what multiple users are doing.  I'll put the cdscan output (xml files) in a subdirectory of /tmp named after the user, rather than /tmp itself.  Then we can cross our fingers, and re-open the issue if that wasn't enough.

**Comment by painter1** [comment]
Done, in branch cachepath; I'll issue a pull request momentarily.
