### ISSUE TITLE
tier1b broken

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcmetrics#268]
This is actually a super easy fix (I figured it out for Yuying when she was trying to run metadiags on the cloud set); this block of code: https://github.com/UV-CDAT/uvcmetrics/blob/09b7eb7ed1313254daae5d2b543d23fb080e7f8a/src/python/frontend/form_filenames.py#L134-L151

needs to have a check if the plotset's name begins with "tier1b_"; in testing with Yuying, I added it to line 139 as an alternative to it just being a numbered plotset, and that seemed to work for `tier1b_clouds`.

**Comment by painter1** [comment]
Fixed.   The fix is general enough to cover most future situations.  In this case, a file name will begin with tier1b_clouds_set5_, showing both the diagnostic collection name (a key in amwgmaster.py) and the plot set name.   If the diagnostic collection name were '5', file names would begin with 'set5_'.  This applied both to filenames which the function filenames() provides to the viewer, and the filenames which are computed elsewhere and used for writing the actual files.
