### ISSUE TITLE
AMWG fatal error in uvcdat

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcmetrics#98]
When trying to set the path in the latest uvcdat  gui, I get the following error

Traceback (most recent call last):
  File "/usr/local/uvcdat/03_04_2015/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 260, in setDS1Path
    if len(self.opts._opts['model']) == 0:
KeyError: 'model'

**Comment by isubsmith** [comment]
Make sure you grab the UVCDAT 89 bug fixes. They are in the latest vistrails branch.


Brian Smith
smithbe@ornl.gov<mailto:smithbe@ornl.gov>



On Mar 4, 2015, at 6:01 PM, James McEnerney <notifications@github.com<mailto:notifications@github.com>> wrote:


When trying to set the path in the latest uvcdat gui, I get the following error

Traceback (most recent call last):
File "/usr/local/uvcdat/03_04_2015/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 260, in setDS1Path
if len(self.opts._opts['model']) == 0:
KeyError: 'model'

�

**Comment by painter1** [comment]
This is fundamentally a build system bug, and one which we will see again.
The workaround is easy enough so that I've labeled this issue a "won't fix" bug, and will close it.

The problem comes from how the diagnostics files are included in the UV-CDAT distribution.  The file dates are more recent than the actual dates of the last commit.  Maybe they are the dates that they were made available to the UV-CDAT build system.  But whatever the reason, a
  python setup.py install
in the latest working version of the diagnostics, will check the file dates to decide which of them need to be updated.  So it gets it wrong, and you end out with a messy combination of the latest diagnostic code and some old last-release diagnostic code.

The workaround is to take note of where the install is putting the .py files.   It will be something like .../site-packages/metrics/.  Delete everything in there!  Then re-issue the command
  python setup.py install
from the usual place, the top of the diagnostics source tree.

BTW, Jim has verified that "python setup.py clean" will not help.

**Comment by painter1** [comment]
BTW, deleting the contents of .../site-packages/metrics/ is now part of my standard procedure for building a new UV-CDAT.  It's not necessary for someone who is satisfied with the diagnostics version that comes with the UV-CDAT distribution.

**Comment by doutriaux1** [comment]
i think we could add a to the build setup to pull vistrails everytime we do setup.py install. it shouldn't be too hard

**Comment by doutriaux1** [comment]
creating a new issue for this
